version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:latest
    resource_class: medium

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: CI=true npm run build

  test:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run test

workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - test
